# Generated by Django 5.2.6 on 2025-09-10 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "vector_index_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "vectorization_status",
                    models.CharField(
                        choices=[
                            ("pending", "待處理"),
                            ("processing", "處理中"),
                            ("completed", "已完成"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("vectorization_error", models.TextField(blank=True, null=True)),
                (
                    "vectorization_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "conversations",
                    models.ManyToManyField(
                        blank=True, related_name="pdfs", to="conversations.conversation"
                    ),
                ),
            ],
            options={
                "db_table": "pdf_documents",
                "ordering": ["-upload_time"],
            },
        ),
    ]
