# Generated by Django 5.2.6 on 2025-09-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfdocument",
            name="conversations",
        ),
    ]
