# Generated by Django 5.2.6 on 2025-09-10 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("llm", "LLM設定"),
                            ("rag", "RAG設定"),
                            ("system", "系統設定"),
                            ("ui", "介面設定"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_encrypted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_configs",
                "indexes": [
                    models.Index(
                        fields=["config_type", "key"],
                        name="system_conf_config__1100c1_idx",
                    )
                ],
                "unique_together": {("config_type", "key")},
            },
        ),
    ]
