# Generated by Django 5.2.6 on 2025-09-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_config", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemconfig",
            options={"verbose_name": "系統配置", "verbose_name_plural": "系統配置"},
        ),
        migrations.RemoveIndex(
            model_name="systemconfig",
            name="system_conf_config__1100c1_idx",
        ),
        migrations.AlterUniqueTogether(
            name="systemconfig",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="chunk_overlap",
            field=models.IntegerField(default=200, help_text="分塊重疊大小"),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="chunk_size",
            field=models.IntegerField(default=1024, help_text="文本分塊大小"),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="gemini_api_key",
            field=models.CharField(
                blank=True, help_text="Gemini API Key", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="gemini_model",
            field=models.CharField(
                default="gemini-pro", help_text="Gemini 模型名稱", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="max_file_size",
            field=models.BigIntegerField(
                default=104857600, help_text="最大文件大小 (bytes)"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="system_prompt",
            field=models.TextField(
                default="你是一個專業的學術助手，專門協助用戶理解和分析 PDF 文件內容。請根據提供的文檔內容準確回答問題，並標註引用來源。",
                help_text="系統提示詞",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="top_k",
            field=models.IntegerField(default=5, help_text="檢索結果數量"),
        ),
        migrations.AlterModelTable(
            name="systemconfig",
            table=None,
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="config_type",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="description",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="is_encrypted",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="key",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="value",
        ),
    ]
