# Generated by Django 5.2.6 on 2025-09-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_config", "0002_alter_systemconfig_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="rag_enabled",
            field=models.BooleanField(default=True, help_text="是否啟用 RAG 模式"),
        ),
    ]
