# Generated by Django 5.2.6 on 2025-09-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_config", "0003_systemconfig_rag_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="process_images",
            field=models.BooleanField(default=False, help_text="是否處理 PDF 中的圖片"),
        ),
    ]
