# Generated by Django 5.2.6 on 2025-09-10 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
        ("pdfs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="citation",
            name="pdf_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations",
                to="pdfs.pdfdocument",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="citations",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="conversations.citation"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="conversations.conversation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="citation",
            unique_together={("pdf_document", "page_number", "start_char", "end_char")},
        ),
    ]
