# Generated by Django 5.2.6 on 2025-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_initial"),
        ("pdfs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pdfs',
            field=models.ManyToManyField(blank=True, help_text='與此對話關聯的 PDF 文檔', related_name='conversations', to='pdfs.pdfdocument'),
        ),
    ]
