# Generated by Django 5.2.6 on 2025-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_auto_20250911_1916"),
        ("pdfs", "0002_remove_pdfdocument_conversations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="pdfs",
            field=models.ManyToManyField(
                blank=True, help_text="與此對話關聯的 PDF 文檔", to="pdfs.pdfdocument"
            ),
        ),
    ]
