# Generated by Django 5.2.6 on 2025-09-11 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0004_alter_conversation_pdfs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "image_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="conversations.imageattachment"
            ),
        ),
    ]
