# Generated by Django 5.2.6 on 2025-09-17 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_initial_folder_and_migrate_conversations(apps, schema_editor):
    """創建初始文件夾並將現有對話移動到其中"""
    Folder = apps.get_model('conversations', 'Folder')
    Conversation = apps.get_model('conversations', 'Conversation')

    # 創建初始文件夾
    initial_folder = Folder.objects.create(name='未分類')

    # 將所有現有的對話移動到初始文件夾
    conversations_without_folder = Conversation.objects.filter(folder__isnull=True)
    for conversation in conversations_without_folder:
        conversation.folder = initial_folder
        conversation.save()


def reverse_initial_folder_migration(apps, schema_editor):
    """逆向遷移：清除文件夾關聯"""
    Conversation = apps.get_model('conversations', 'Conversation')

    # 將所有對話的文件夾設為 None
    Conversation.objects.update(folder=None)


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0005_imageattachment_message_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "folders",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="對話所屬的文件夾",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="conversations.folder",
            ),
        ),
        migrations.RunPython(
            create_initial_folder_and_migrate_conversations,
            reverse_initial_folder_migration,
        ),
    ]
