# Generated by Django 5.2.6 on 2025-10-18 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0006_folder_conversation_folder"),
        ("pdfs", "0002_remove_pdfdocument_conversations"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[("highlight", "高亮"), ("text", "文字方块")],
                        help_text="注释类型",
                        max_length=20,
                    ),
                ),
                ("page_number", models.IntegerField(help_text="页码")),
                ("x", models.FloatField(help_text="X坐标百分比")),
                ("y", models.FloatField(help_text="Y坐标百分比")),
                ("width", models.FloatField(help_text="宽度百分比")),
                ("height", models.FloatField(help_text="高度百分比")),
                (
                    "color",
                    models.CharField(
                        default="yellow", help_text="高亮颜色", max_length=20
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, help_text="文字方块内容", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="所属对话",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_annotations",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "pdf_document",
                    models.ForeignKey(
                        help_text="所属PDF文档",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="pdfs.pdfdocument",
                    ),
                ),
            ],
            options={
                "db_table": "pdf_annotations",
                "ordering": ["pdf_document", "page_number", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "pdf_document"],
                        name="pdf_annotat_convers_a94948_idx",
                    ),
                    models.Index(
                        fields=["page_number"], name="pdf_annotat_page_nu_2ae75e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PDFReadingState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("current_page", models.IntegerField(default=1, help_text="当前页码")),
                (
                    "scroll_position",
                    models.FloatField(default=0, help_text="滚动位置百分比"),
                ),
                ("zoom_level", models.FloatField(default=1.0, help_text="缩放级别")),
                (
                    "last_read_at",
                    models.DateTimeField(auto_now=True, help_text="最后阅读时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="所属对话",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_reading_states",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "pdf_document",
                    models.ForeignKey(
                        help_text="所属PDF文档",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_states",
                        to="pdfs.pdfdocument",
                    ),
                ),
            ],
            options={
                "db_table": "pdf_reading_states",
                "ordering": ["-last_read_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "pdf_document"],
                        name="pdf_reading_convers_e09818_idx",
                    )
                ],
                "unique_together": {("conversation", "pdf_document")},
            },
        ),
    ]
